[package]
name = "smt160-driver"
version = "0.7.0"
edition = "2024"
authors = ["Faez Barghasa <faez.barghasa@gmail.com>"]
description = "High-precision, zero-jitter async driver for SMT160 sensors on STM32"
license = "MIT OR Apache-2.0"

[dependencies]
fixed = { version = "1.23", features = ["num-traits"] }
fugit = "0.3"
bitflags = { version = "2.4" }
defmt = { version = "0.3", optional = true }
embedded-hal = "1.0"
embedded-hal-async = "1.0"
embedded-storage = "0.3"
cfg-if = "1.0"
libm = "0.2"
embassy-sync = { version = "0.6", features = ["defmt"] }
rtic-monotonics = { version = "2.1", features = ["cortex-m-systick"] }
stm32f1xx-hal = { version = "0.10.0", features = ["rt", "stm32f103"] }
portable-atomic = { version = "1.6", features = ["critical-section"] }
critical-section = "1.1"
serde = { version = "1.0", default-features = false, features = ["derive"], optional = true }

[dev-dependencies]
rtic = { version = "2.1", features = ["thumbv7-backend"] }
panic-probe = { version = "0.3", features = ["print-defmt"] }
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.3"
defmt-rtt = "0.4.1"

[features]
default = ["defmt"]
std = []
defmt = ["dep:defmt", "embassy-sync/defmt", "fixed/defmt"]
serde = ["dep:serde", "bitflags/serde", "fixed/serde"]

