[package]
name = "smt160-driver"
version = "0.6.0"
edition = "2024"
description = "A fixed-point, async-friendly driver for the SMT160 temperature sensor"

[dependencies]
fixed = { version = "1.27", features = ["az", "defmt"] }
fixed-macro = "1.2"
az = "1.2"
bitflags = { version = "2.6", default-features = false }
embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
fugit = "0.3.7"
critical-section = "1.1.2"
defmt = { version = "0.3", optional = true }
defmt-rtt = { version = "0.4", optional = true }
stm32f1xx-hal = { version = "0.11.0", features = ["medium", "stm32f103"], optional = true }
embedded-storage = "0.3"
cfg-if = "1.0"
libm = "0.2"

[dev-dependencies]
rtic = { version = "2.1", features = ["thumbv7-backend"] }
rtic-monotonics = { version = "2.1", features = ["cortex-m-systick"] }
cortex-m = "0.7.7"
cortex-m-rt = "0.7.3"
panic-probe = { version = "0.3.1", features = ["print-defmt"] }
panic-halt = "1.0.0"
nb = "1.1.0"
proptest = "1.5.0"


[features]
default = ["defmt", "stm32f1xx"]
defmt = ["dep:defmt", "dep:defmt-rtt"]
defmt-rtt = ["dep:defmt-rtt"]
stm32f1xx = ["dep:stm32f1xx-hal"]

[profile.release]
panic = "abort"
codegen-units = 1
debug = true
lto = true